config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :users do 
    resources :workouts do 
      resources :exercises, only: [:new, :create, :show], shallow: true
    end
    resources :date_ofs, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
    end
  end

  root 'users#main'

  post '/users/:id/myworkout/', to: 'users#myworkout'
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  get '/exercises', to: 'exercises#index'

  get '/:id/add_to_workout', to: 'exercises#add_to_workout'

end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password
    
    has_many :date_ofs
    has_many :workouts
    has_many :exercises, through: :workouts

    validates :username, presence: true
    # validates :password, presence: true
    validates :name, presence: true
    validates :username, uniqueness: true
    validates :age, presence: true
    validates :weight, presence: true
    validates :age, numericality: true
    validates :weight, numericality: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:show, :edit, :update, :destroy, :myworkout]
    skip_before_action :authenticate, only: [:new, :create, :destroy, :main]

    def main
        render :main
    end

    def myworkout
        # puts params[:workout][:id]
        # puts params[:id]
        # puts @user.id

        @workout = @user.workouts.find(params[:workout][:id])
        @exercise = Exercise.find(params[:exercise_id])
        @workout.exercises << @exercise
        redirect_to user_workout_path(id: @workout.id, user_id: session[:user_id])
    end 
    
    
    def show
        # current_user = User.find_by(id: session[:user_id])
        # if @user
        #     render :show
        # else
        #     flash[:error] = "You must be logged in to view this page."
        #     redirect_to login_path
        # end
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to @user
        else
            flash[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def edit
    end

    def update
        @user.update(user_params_with_args(:age, :weight))
        if @user.save
            redirect_to @user
        else
            flash[:errors] = @user.errors.full_messages
            render :edit
        end
    end

    def destroy
        @user.destroy
        redirect_to root_path
    end

    private
        def set_user
            @user = User.find_by(id: session[:user_id])
        end

        def user_params_with_args(*args)
            params.require(:user).permit(*args)
        end

        def user_params
            params.require(:user).permit(:name, :username, :password, :age, :weight, :id)
        end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<style>

    body, html {
        height: 100%;
    }

    .wrapper {
        padding: 5% 0;   
    }   

    .container {
        border: 5px solid rgba(75, 87, 122, 0.2);
        width: 30%;
        background: rgba(0,0,0,.6);
        box-shadow: 5px 10px #356486;
        color: white;
        text-align: center;
    }

</style>

<body>
    
<div class="background img-fluid" style="background-image: url(https://thumbs.dreamstime.com/b/fitness-bodybuilding-background-dumbbells-gym-floor-top-view-fitness-bodybuilding-concept-background-product-photograph-108091636.jpg); background-size:cover; background-position: center; background-repeat: no-repeat; background-size: cover; height:120%">

    <div class="wrapper">
        <div class="container rounded">
            <h1>Edit User Form</h1>
            <%= form_for @user do |f| %>
                
                <%= f.label :age %>
                <%= f.text_field :age %><br>

                <%= f.label :weight %>
                <%= f.text_field :weight %><br>
                
                <div class="button">
                <%= f.submit %>
                </div>

            <% end %>
        </div>
    </div>
</div>

app/views/users/main.html.erb
    <style>
        body, html {
            height: 100%;
        }


    body, html {
        height: 100%;
    }

    .wrapper {
        padding: 5% 0; 
    }


        .background {
            background-image: url('https://www.mensjournal.com/wp-content/uploads/mf/crossfit-snatch.jpg');
            height: 100%;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>

<body>
<div class="background"></div> 
    <div class="centered">
        <div class="container">
            <div class="centered">
                <div class="btn-group-vertical">
                    <a class="btn btn-secondary mybg" href=login role="button">Login</a><br>
                    <!--%= link_to "Login", login_path %-->
                    <a class="btn btn-secondary mybg" href='/users/new' role="button">Create Account</a>
                    <!--%= link_to "Create Account", new_user_path %-->
                </div>

            </div>
        </div>
    </div> 
    
</div>

</body>

app/views/users/new.html.erb
<style>

        body, html {
            height: 100%;
        }

        .wrapper {
            padding: 5% 0;
           
        }

        .container {
            border: 5px solid rgba(75, 87, 122, 0.2);
            width: 25%;
            background: #356486;
        }

        .form-groups{
            margin-top: 10px;
        }

        .background {
            background-image: url('https://thumbs.dreamstime.com/b/fitness-bodybuilding-background-dumbbells-gym-floor-top-view-fitness-bodybuilding-concept-background-product-photograph-108091636.jpg');
            height: 100%;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
        
    </style>


<div class="background img-fluid" style="background-image: url('https://thumbs.dreamstime.com/b/fitness-bodybuilding-background-dumbbells-gym-floor-top-view-fitness-bodybuilding-concept-background-product-photograph-108091636.jpg'); height: 100%; background-position: center; background-repeat: no-repeat; background-size: cover;"> 

<div class="wrapper">


    <div class="container rounded">
        <h1 class="d-flex justify-content-center text-light">New User</h1>
        <%= form_tag @user do %>
            <% if flash[:errors] %>
                <% flash[:errors].each do |err| %>
                    <p><%= err %></p>
                <% end %>
             <% end %>
    <div class="form-groups text-center text-light">
    <%= label_tag :for, "Username " %>
    <%= text_field_tag :"user[username]" %><br>
    <%= label_tag :for, "Password " %>
    <%= password_field_tag :"user[password]" %><br>
    <%= label_tag :for, "Name " %>
    <%= text_field_tag :"user[name]" %><br>
    <%= label_tag :for, "Age " %>
    <%= text_field_tag :"user[age]" %><br>
    <%= label_tag :for, "Weight " %>
    <%= text_field_tag :"user[weight]" %><br>

    <%= submit_tag 'Create User' %><br>
    </div>
<% end %>

<div class="centered text-center">
    <%= link_to "Cancel", '/' %>
</div>
    </div>

app/views/users/show.html.erb
<style>

    body, html {
        height: 100%;
    }
        

        .wrapper {
            padding: 5% 0;
           
        }

        .container {
            border: 5px solid rgba(75, 87, 122, 0.2);
            width: 30%;
            background: rgba(0,0,0,.6);
            box-shadow: 5px 10px #356486;
        }

        .background {
            background-image: url('https://thumbs.dreamstime.com/b/fitness-bodybuilding-background-dumbbells-gym-floor-top-view-fitness-bodybuilding-concept-background-product-photograph-108091636.jpg');
            height: 100%;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>


    .wrapper {
        padding: 5% 0;   
    }   


    <div class="background img-fluid" style="background-image: url('https://thumbs.dreamstime.com/b/fitness-bodybuilding-background-dumbbells-gym-floor-top-view-fitness-bodybuilding-concept-background-product-photograph-108091636.jpg'); height: 100%; background-position: center; background-repeat: no-repeat; background-size: cover;"> 

    <div class="wrapper">

    <div class="container rounded">
        <h1 class="d-flex justify-content-center text-light">My Fitness Profile</h1><br>
        <img src="https://i.stack.imgur.com/34AD2.jpg" class="rounded mx-auto d-block" alt="That's Me!"><br>
        <h3 class="d-flex justify-content-center text-light"><%= @user.name %></h3><br>

        <p class="d-flex justify-content-center text-light">Age: <%= @user.age %></p>
        <p class="d-flex justify-content-center text-light">Weight: <%= @user.weight %> lbs</p>
        <p class="d-flex justify-content-center"><%= link_to "Edit Profile", edit_user_path(@user) %></p>

        <div class="d-flex justify-content-center">
            <%= link_to "Calendar View", user_date_ofs_path(@user), class: "btn btn-secondary mybg btn-sm mr-1" %>
            <%= link_to "All My Workouts", user_workouts_path(@user), class: "btn btn-secondary mybg btn-sm" %>
        </div><br>

        <p class="d-flex justify-content-center"><%= link_to "Logout", logout_path %></p>
    </div>
</div>
</div>


</body>