config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :users do 
    resources :workouts do 
      resources :exercises, only: [:new, :create, :show], shallow: true
    end
    resources :date_ofs, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
    end
  end

  root 'users#main'

  post '/users/:id/myworkout/', to: 'users#myworkout'
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  get '/exercises', to: 'exercises#index'

  get '/:id/add_to_workout', to: 'exercises#add_to_workout'

end

app/models/date_of.rb
class DateOf < ApplicationRecord

    belongs_to :user
   
    def workouts
        @workout = Workout.where(workout_date: self.date_of)
    end

end

app/controllers/date_ofs_controller.rb
class DateOfsController < ApplicationController

    require 'date'
    before_action :set_date, only: [:show, :edit, :update, :destroy]

    def index
        @date_ofs = DateOf.all
    end

    def new
        @date_of = DateOf.create(date_params)
        redirect_to user_date_of_path(id: @date_of.id)
    end

    # remove new page, when new date_of created, redirect to date show page

    # def create
    #     redirect_to user_date_of_path(id: @date_of.id)
    # end

    def show
    end

    def edit
    end

    def update
        @date.update(date_params)
        redirect_to @date
    end
        
    def destroy
        @date.destroy
        redirect_to user_path(@date.user.id)
    end

    private
        def set_date
            @date = DateOf.find_by(id: params[:id], user_id: session[:user_id])
        end

        def date_params
            params.permit(:date_of, :user_id)
        end

end

app/helpers/date_ofs_helper.rb
module DateOfsHelper
end

app/views/date_ofs/index.html.erb
    <style>

    html, body{
        margin: 0;
    }

    .container{
        padding: 5px 0 5px 0;
        display: flex;
        justify-content: space-around;
    }

    .mx-auto{
        width: 75%;
        justify-content: center;
    }

    </style>

</head>

<body>
<div class="mx-auto">
<%= month_calendar do |date| %>
    <% if DateOf.find_by(date_of: date, user_id: session[:user_id]) %>
        <%= link_to date.day, user_date_of_path(user_id: session[:user_id], id: DateOf.find_by(date_of: date).id) %>
    <% else %>
        <%= link_to date.day, new_user_date_of_path(user_id: session[:user_id], date_of: date) %>
    <% end %>
<% end %>
    <a class="btn btn-primary" href='/users/<%= @user.id %>' role="button" >Back</a>
    </div>
</div>
</body>
</html>

app/views/date_ofs/new.html.erb
<h1><%= @date_of.date_of.strftime("%B %d") %> Stats</h1>

<p>Empty. Please add information for the day.</p>

<%= link_to "Back", user_date_ofs_path(@user) %>

app/views/date_ofs/show.html.erb
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    
    <title></title>

    <style>

    html, body{
        margin: 0;
    }

    .container{
        padding: 5px 0 5px 0;
        display: flex;
        justify-content: space-around;
    }

    </style>

</head>

<body>
<div class="container">
<h1><%= @date.date_of.strftime("%B %d") %></h1>
</div>

<div class="container">
<h3>Workout</h3>
</div>

<div class="container">

<% if @date.workouts.count > 0 %>
    <% @date.workouts.each do |workout| %>
        <div class="card text-white bg-dark mb-3" style="width: 18rem;">
        <% if workout.exercises.count > 0 %>
            <img src="<%= workout.exercises[(rand 0..(workout.exercises.count-1))].image_url %>" class="card-img-top">
        <% end %>
            <div class="card-body">
                <h5 class="card-title d-flex justify-content-center"><%= workout.name %></h5>
                <a href="/users/<%= workout.user_id %>/workouts/<%= workout.id %>" class="btn btn-primary d-flex justify-content-center">View Workout</a>
            </div>
        </div>
    <% end %>
<% else %>
    <p><%= link_to "No Workouts. Please add a workout", user_workouts_path(user_id: session[:user_id]) %>.</p>
<% end %>

</div>

<div class="container">
<a href="/users/<%= @date.user_id %>/date_ofs" class="btn btn-primary d-flex justify-content-center">Back</a>
</div>
</body>
</html>