config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :users do 
    resources :workouts do 
      resources :exercises, only: [:new, :create, :show], shallow: true
    end
    resources :date_ofs, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
    end
  end

  root 'users#main'

  post '/users/:id/myworkout/', to: 'users#myworkout'
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  get '/exercises', to: 'exercises#index'

  get '/:id/add_to_workout', to: 'exercises#add_to_workout'

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

    def index
        @exercises = Exercise.all
    end

    # def new
    #     @exercise = Exercise.new
    # end

    def show
        @exercise = Exercise.find(params[:id])
    end

    # def create
    #     @exercise = Exercise.create(exercise_params)
    # end

    # def add_to_workout
    #     # @workout = Workout.find_by(id: workout.id)
    #     @exercise = Exercise.find(params[:id])
    #     @exercise.add_to_workout(@workout)
    #     redirect_to @workout
    # end

    private

    def exercise_params
        params.require(:exercise).permit(:exercise_name, :image_url, :page_url, :exercise_difficulty, :exercise_impact_level, :target_body_parts, :exercise_video, :category)
    end

end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/index.html.erb
<style>

    html, body {
        margin: 0;
    }

    .container{
        width: 800px;
        left: 15%;
        margin: 5px 0px 0 20px;
    }

    .sidenav{
        background-color: #356486;
        height: 100%; 
        width: 10%; 
        position: fixed; 
        z-index: 1; 
        top: 7%; 
        left: 0; 
        overflow-x: hidden;
        padding-top: 20px;
    }

    .sidenav a{
        padding: 6px 8px 6px 16px;
        text-decoration: none;
        font-size: 15px;
        color: whitesmoke;
        display: block;
    }

    .sidenav a:hover {
        color: #f1f1f1;
    }

    .main {
        margin-left: 15%;
        length: 100%;
        width: 100%;
        padding: 0px 10px;
    }

    .button{
        margin-left: 317px;
        width:200px;
        justify-content: center;
    }

    .top-box{
        margin-left: -585px;
        text-align: center;
        justify-content: center;
    }


</style>

<div class="container">
    <div class="sidenav" style="">
        <a href="#upper_body">Upper Body</a>
        <a href="#lower_body">Lower Body</a>
        <a href="#core">Core</a>
        <a href="#back">Back</a>
        <a href="#cardio">Cardio</a>
        <a href="#yoga">Yoga</a>
        <a href="#pilates">Pilates</a>
        <a href="#stretching">Stretching</a>
        <a href="/exercises">Back to Top</a>
    </div>
</div>


<div class="main">

    <h1 class="top-box">All Exercises</h1>

        <div class="button">
        <a href="/users/<%= session[:user_id] %>/workouts" class="btn btn-primary d-flex justify-content-center">Return to Workouts</a>
        </div>

<div class="container">
    
    <div id="upper_body"><br><br><br><h3>Upper Body</h3></div>
    
    <div class="container">
        <div class="row">
            <% Exercise.upper_body.each do |exercise| %>
                <div class="col-6 col-6">
                    <div class="card text-white bg-dark mb-5" style="width: 18rem;">
                        <img src="<%= exercise.image_url %>" class="card-img-top" >
                        <div class="card-body">
                            <h5 class="card-title d-flex justify-content-center"><%= exercise.exercise_name %></h5>
                            <a href="/exercises/<%= exercise.id %>" class="btn btn-primary d-flex justify-content-center">View Exercise</a>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>


<div id="lower_body"><br><br><br><h3>Lower Body</h3>

<div class="container">
    <div class="row">
        <% Exercise.lower_body.each do |exercise| %>
            <div class="col-6 col-6">
                <div class="card text-white bg-dark mb-3" style="width: 18rem;">
                    <img src="<%=exercise.image_url%>" class="card-img-top" >
                    <div class="card-body">
                        <h5 class="card-title d-flex justify-content-center"><%= exercise.exercise_name %></h5>
                        <a href="/exercises/<%= exercise.id %>" class="btn btn-primary d-flex justify-content-center">View Exercise</a>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>
</div>

<div id="core"><h3><br><br><br>Core</h3>

<div class="container">
    <div class="row">
        <% Exercise.core.each do |exercise| %>
            <div class="col-6 col-6">
                <div class="card text-white bg-dark mb-3" style="width: 18rem;">
                    <img src="<%=exercise.image_url%>" class="card-img-top" >
                    <div class="card-body">
                        <h5 class="card-title d-flex justify-content-center"><%= exercise.exercise_name %></h5>
                        <a href="/exercises/<%= exercise.id %>" class="btn btn-primary d-flex justify-content-center">View Exercise</a>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>
</div>

<div id="back"><h3><br><br><br>Back</h3>

<div class="container">
    <div class="row">
        <% Exercise.back.each do |exercise| %>
            <div class="col-6 col-6">
                <div class="card text-white bg-dark mb-3" style="width: 18rem;">
                    <img src="<%=exercise.image_url%>" class="card-img-top" >
                    <div class="card-body">
                        <h5 class="card-title d-flex justify-content-center"><%= exercise.exercise_name %></h5>
                        <a href="/exercises/<%= exercise.id %>" class="btn btn-primary d-flex justify-content-center">View Exercise</a>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>
</div>

<div id="cardio"><h3><br><br><br>Cardio</h3>

<div class="container">
    <div class="row">
        <% Exercise.cardio.each do |exercise| %>
            <div class="col-6 col-6">
                <div class="card text-white bg-dark mb-3" style="width: 18rem;">
                    <img src="<%=exercise.image_url%>" class="card-img-top" >
                    <div class="card-body">
                        <h5 class="card-title d-flex justify-content-center"><%= exercise.exercise_name %></h5>
                        <a href="/exercises/<%= exercise.id %>" class="btn btn-primary d-flex justify-content-center">View Exercise</a>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>
</div>

<div id="yoga"><h3><br><br><br>Yoga</h3>

<div class="container">
    <div class="row">
        <% Exercise.yoga.each do |exercise| %>
            <div class="col-6 col-6">
                <div class="card text-white bg-dark mb-3" style="width: 18rem;">
                    <img src="<%=exercise.image_url%>" class="card-img-top" >
                    <div class="card-body">
                        <h5 class="card-title d-flex justify-content-center"><%= exercise.exercise_name %></h5>
                        <a href="/exercises/<%= exercise.id %>" class="btn btn-primary d-flex justify-content-center">View Exercise</a>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>
</div>

<div id="pilates"><h3><br><br><br>Pilates</h3>

<div class="container">
    <div class="row">
        <% Exercise.pilates.each do |exercise| %>
            <div class="col-6 col-6">
                <div class="card text-white bg-dark mb-3" style="width: 18rem;">
                    <img src="<%=exercise.image_url%>" class="card-img-top" >
                    <div class="card-body">
                        <h5 class="card-title d-flex justify-content-center"><%= exercise.exercise_name %></h5>
                        <a href="/exercises/<%= exercise.id %>" class="btn btn-primary d-flex justify-content-center">View Exercise</a>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>
</div>

<div id="stretching"><h3><br><br><br>Stretching</h3>

<div class="container">
    <div class="row">
        <% Exercise.stretching.each do |exercise| %>
            <div class="col-6 col-6">
                <div class="card text-white bg-dark mb-3" style="width: 18rem;">
                    <img src="<%=exercise.image_url%>" class="card-img-top" >
                    <div class="card-body">
                        <h5 class="card-title d-flex justify-content-center"><%= exercise.exercise_name %></h5>
                        <a href="/exercises/<%= exercise.id %>" class="btn btn-primary d-flex justify-content-center">View Exercise</a>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>
</div>
</div>
</div>
</div>

app/views/exercises/show.html.erb
    <div class="container d-flex justify-content-center">
        <h1><%= @exercise.exercise_name %></h1>
    </div>
    
    <div class="container d-flex justify-content-center w-50">
        <video src=<%= @exercise.exercise_video %> autoplay loop width="600px" ></video><br>
    </div>

    <%= form_tag "/users/#{session[:user_id]}/myworkout/", method: "post", class: "form-inline justify-content-center" do %>
    <div class="form-group mx-4">
        <%= collection_select(:workout, :id, Workout.where(user_id: session[:user_id]), :id, :name, class: "form-control") %>
    </div>
    <%= hidden_field_tag "exercise_id", @exercise.id %>
    <%= submit_tag("Add to Workout", class: "btn btn-primary mybg btn-sm") %>
    <% end %>

 <div class="container">
    
    <div class="row">
        <div class="col-4 text-center">
            <p>Category: <%= @exercise.category %></p>
        </div>
        <div class="col-4 text-center">
            <p><%= @exercise.exercise_difficulty %></p>
        </div> 
        <div class="col-4 text-center">
            <p><%= @exercise.exercise_impact_level %></p>
        </div> 
    </div>
    
    <div class="row justify-content-center">
        
        <div class="col-6 text-center">
            <p><%= @exercise.target_body_parts %></p>
        </div>
    </div>

</div>

<div class="d-flex justify-content-center">
    <%= link_to "Back", exercises_path, class: "btn btn-primary mybg btn-sm" %>
</div>